apiVersion: v1
kind: Service
metadata:
  name: closet-service
spec:
  selector:
    app.kubernetes.io/name: closet-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort